parserOptions:
  sourceType: 'module'

env:
  es6: true
  browser: true

extends: 'htmlacademy/es6'

parserOptions:
  sourceType: 'module'

env:
  es6: true
  browser: true
  mocha: true

extends: 'htmlacademy/es6'